"""
Composer Agent — Plan-and-Execute Architecture
=============================================

Design overview
---------------
1. PLAN   – The LLM analyses the user's request and generates a structured
             CompositionPlan (genre, mood, key, tempo, instruments, structure …).

2. EXECUTE – Four sequential nodes, each corresponding to one creative stage:
               lyrics  →  arrangement  →  melody  →  full_song

   Each node receives the accumulated state (plan + all previous outputs) so
   later stages can build naturally on earlier ones.

3. SYNTHESISE – The full_song node already produces the final formatted output,
                so no extra synthesis step is needed.

Graph topology
--------------
  [START] → planner → lyrics → arrangement → melody → full_song → [END]

State
-----
  ComposerState carries every artifact produced so far plus the original
  user request, making the whole pipeline fully traceable.
"""

from __future__ import annotations

from typing import TypedDict, Optional

from langchain_core.callbacks import adispatch_custom_event
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.runnables import RunnableConfig
from langchain_core.tools import tool
from langgraph.graph import END, StateGraph
from loguru import logger
from pydantic import BaseModel, Field

from agent.base import create_model
from prompt.prompt import (
    COMPOSER_ARRANGEMENT_PROMPT,
    COMPOSER_FULL_SONG_PROMPT,
    COMPOSER_LYRICS_PROMPT,
    COMPOSER_MELODY_PROMPT,
    COMPOSER_PLANNER_PROMPT,
)


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


class CompositionPlan(BaseModel):
    """Structured composition plan generated by the planner node."""

    title: str = Field(description="Song title")
    genre: str = Field(description="Music genre (e.g. pop, rock, jazz, R&B)")
    mood: str = Field(description="Emotional mood (e.g. melancholic, upbeat, romantic)")
    theme: str = Field(description="Core narrative or thematic idea of the song")
    key: str = Field(description="Musical key (e.g. C major, A minor, F# minor)")
    tempo: str = Field(description="Tempo description (e.g. slow 70 BPM, upbeat 120 BPM)")
    instruments: list[str] = Field(description="Instruments to include in the arrangement")
    structure: str = Field(
        description="Song structure using section names separated by dashes "
        "(e.g. intro-verse-chorus-verse-chorus-bridge-chorus-outro)"
    )
    reasoning: str = Field(description="Brief explanation of the creative choices made")


# ---------------------------------------------------------------------------
# Graph state
# ---------------------------------------------------------------------------


class ComposerState(TypedDict):
    """Shared state that flows through every node in the graph."""

    user_request: str

    # Populated by the planner node
    plan: Optional[dict]          # serialised CompositionPlan

    # Populated by each execution node
    lyrics: str
    arrangement: str
    melody: str
    full_song: str


# ---------------------------------------------------------------------------
# Node factories
# (Each factory closes over the shared `model` instance so the graph can be
#  compiled once at module level without re-creating the LLM on every call.)
# ---------------------------------------------------------------------------


def _make_planner_node(model):
    """
    Planner node — analyses the user request and returns a CompositionPlan.

    Uses structured output so the plan is always machine-readable and can be
    passed to subsequent nodes as keyword arguments.
    """
    structured_model = model.with_structured_output(CompositionPlan)

    async def planner_node(state: ComposerState, config: RunnableConfig) -> dict:
        logger.info("[composer] planner: analysing request …")

        plan: CompositionPlan = await structured_model.ainvoke(
            [
                SystemMessage(content=COMPOSER_PLANNER_PROMPT),
                HumanMessage(content=state["user_request"]),
            ]
        )

        logger.info(f"[composer] plan: title={plan.title!r}, genre={plan.genre!r}, "
                    f"mood={plan.mood!r}, key={plan.key}, tempo={plan.tempo}")

        await adispatch_custom_event(
            "composer.plan_available",
            {"plan": plan.model_dump()},
            config=config,
        )

        return {"plan": plan.model_dump()}

    return planner_node


def _make_lyrics_node(model):
    """
    Lyrics node — writes the full song lyrics based on the composition plan.

    Substitutes plan fields into the prompt template so the LLM has all the
    creative parameters it needs without having to re-infer them.

    NOTE: If you want to use a dedicated lyric-generation API or a
    fine-tuned model, replace the `model.ainvoke` call here and delegate to
    `tools.composer.write_lyrics` instead.
    """

    async def lyrics_node(state: ComposerState, config: RunnableConfig) -> dict:
        logger.info("[composer] writing lyrics …")
        await adispatch_custom_event("composer.step_start", {"step": "lyrics"}, config=config)

        plan = state["plan"]
        system_prompt = COMPOSER_LYRICS_PROMPT.format(
            mood=plan["mood"],
            theme=plan["theme"],
            genre=plan["genre"],
            structure=plan["structure"],
        )

        result = await model.ainvoke(
            [
                SystemMessage(content=system_prompt),
                HumanMessage(content=f"User request: {state['user_request']}"),
            ]
        )

        logger.info("[composer] lyrics written.")
        await adispatch_custom_event("composer.step_complete", {"step": "lyrics"}, config=config)
        return {"lyrics": result.content}

    return lyrics_node


def _make_arrangement_node(model):
    """
    Arrangement node — designs chord progressions, instrumentation layers,
    and production style based on the plan and the finished lyrics.

    NOTE: Replace the `model.ainvoke` call here to integrate with a real
    chord / arrangement generation service (e.g. HookTheory, a DAW script,
    or a custom ML model).  You can call `tools.composer.create_arrangement`
    once you have implemented that stub.
    """

    async def arrangement_node(state: ComposerState, config: RunnableConfig) -> dict:
        logger.info("[composer] creating arrangement …")
        await adispatch_custom_event("composer.step_start", {"step": "arrangement"}, config=config)

        plan = state["plan"]
        system_prompt = COMPOSER_ARRANGEMENT_PROMPT.format(
            genre=plan["genre"],
            mood=plan["mood"],
            key=plan["key"],
            tempo=plan["tempo"],
            instruments=", ".join(plan["instruments"]),
        )

        result = await model.ainvoke(
            [
                SystemMessage(content=system_prompt),
                HumanMessage(
                    content=(
                        f"Lyrics:\n{state['lyrics']}\n\n"
                        f"User request: {state['user_request']}"
                    )
                ),
            ]
        )

        logger.info("[composer] arrangement created.")
        await adispatch_custom_event("composer.step_complete", {"step": "arrangement"}, config=config)
        return {"arrangement": result.content}

    return arrangement_node


def _make_melody_node(model):
    """
    Melody node — composes the main vocal melody given lyrics + arrangement.

    NOTE: Replace the `model.ainvoke` call here to integrate with a real
    melody generation model (e.g. Magenta, MusicGen, a MIDI generation
    library).  You can call `tools.composer.compose_melody` once you have
    implemented that stub.  The output could be ABC notation, a MIDI file
    path, or a structured note list.
    """

    async def melody_node(state: ComposerState, config: RunnableConfig) -> dict:
        logger.info("[composer] composing melody …")
        await adispatch_custom_event("composer.step_start", {"step": "melody"}, config=config)

        plan = state["plan"]
        system_prompt = COMPOSER_MELODY_PROMPT.format(
            key=plan["key"],
            tempo=plan["tempo"],
            genre=plan["genre"],
        )

        result = await model.ainvoke(
            [
                SystemMessage(content=system_prompt),
                HumanMessage(
                    content=(
                        f"Lyrics:\n{state['lyrics']}\n\n"
                        f"Arrangement:\n{state['arrangement']}\n\n"
                        f"User request: {state['user_request']}"
                    )
                ),
            ]
        )

        logger.info("[composer] melody composed.")
        await adispatch_custom_event("composer.step_complete", {"step": "melody"}, config=config)
        return {"melody": result.content}

    return melody_node


def _make_full_song_node(model):
    """
    Full-song node — assembles everything into a polished final presentation.

    NOTE: In a real pipeline this node would hand all artifacts off to an
    audio-rendering service (Suno, Udio, a custom DAW pipeline, etc.) and
    return a URL or binary audio file instead of a text summary.
    You can call `tools.composer.produce_full_song` once you have
    implemented that stub.
    """

    async def full_song_node(state: ComposerState, config: RunnableConfig) -> dict:
        logger.info("[composer] producing final song …")
        await adispatch_custom_event("composer.step_start", {"step": "full_song"}, config=config)

        plan = state["plan"]
        system_prompt = COMPOSER_FULL_SONG_PROMPT.format(
            title=plan["title"],
            genre=plan["genre"],
            mood=plan["mood"],
        )

        result = await model.ainvoke(
            [
                SystemMessage(content=system_prompt),
                HumanMessage(
                    content=(
                        f"Lyrics:\n{state['lyrics']}\n\n"
                        f"Arrangement:\n{state['arrangement']}\n\n"
                        f"Melody:\n{state['melody']}\n\n"
                        f"User request: {state['user_request']}"
                    )
                ),
            ]
        )

        logger.info("[composer] full song produced.")
        await adispatch_custom_event("composer.step_complete", {"step": "full_song"}, config=config)
        return {"full_song": result.content}

    return full_song_node


# ---------------------------------------------------------------------------
# Graph construction
# ---------------------------------------------------------------------------


def _build_composer_graph():
    """Compile the plan-and-execute LangGraph for music composition."""

    model = create_model()

    builder = StateGraph(ComposerState)

    builder.add_node("planner",     _make_planner_node(model))
    builder.add_node("lyrics",      _make_lyrics_node(model))
    builder.add_node("arrangement", _make_arrangement_node(model))
    builder.add_node("melody",      _make_melody_node(model))
    builder.add_node("full_song",   _make_full_song_node(model))

    # Strict sequential pipeline: each stage depends on the previous one
    builder.set_entry_point("planner")
    builder.add_edge("planner",     "lyrics")
    builder.add_edge("lyrics",      "arrangement")
    builder.add_edge("arrangement", "melody")
    builder.add_edge("melody",      "full_song")
    builder.add_edge("full_song",   END)

    return builder.compile()


# Compiled once at import time; reused across all invocations
_composer_graph = _build_composer_graph()


# ---------------------------------------------------------------------------
# Facade tool — exposes the composer agent to the main agent
# ---------------------------------------------------------------------------


@tool("compose_music", description=(
    "Compose a complete original song for the user. "
    "Handles everything: lyrics, arrangement, melody, and final presentation. "
    "Provide the user's raw music request as the query."
))
async def composer_agent_facade(query: str, config: RunnableConfig) -> str:
    """Invoke the composer sub-agent and return the finished song."""

    logger.info(f"[composer] facade invoked: {query!r}")

    # Strip the parent thread's configurable so the sub-agent starts fresh
    sub_config = RunnableConfig(callbacks=config.get("callbacks"))

    initial_state: ComposerState = {
        "user_request": query,
        "plan": None,
        "lyrics": "",
        "arrangement": "",
        "melody": "",
        "full_song": "",
    }

    result = await _composer_graph.ainvoke(initial_state, config=sub_config)

    logger.info("[composer] facade complete.")
    return result.get("full_song", "Composition failed — no output produced.")
